### PR TITLE
Preliminary PL translations

### PR DESCRIPTION
**Pull request by DubbaThony**
[DRAFT]

Has some questions, and need to double-read it.

Questions:
"The top source will be considered primary" -> is the "top source" as in the best source, or top as in within layout the one graphically above others?
What's difference between "reached_the_end_of_the_queue" and "end_of_queue_reached"?
"check" is as in "to check something" (test for something?)  or check as in checkbox?
"do_you_want_to_import_this_store" - Can I have another string identifier that has the same meaning of "store"? There is no 1:1 translation of "store" as in repository or storage, only for "shop" in polish, so I need to figure out what's it supposed to mean to pick something usable here. Is this same context as "store", "visit_my_store" string?
"stripe_is_a_secure_online_payment_service_that_accepts_major_credit_cards_debit_cards_and_various_localized_payment_methods"
Is it OK to include mention that Stripe supports BLIK (which is very popular in poland, and basically anyone with access to payments online has access to it), something like "supports payment cards and local payment methods like BLIK"
"viewers_are_raiding" - I don't exactly understand the string? Can someone explain please?

Other questionable translations

attempt_to_utilize_byte_ranges
failed_to_fully_backfill_servers
failed_to_backfill_client
data_retry

### CODE REVIEW

**Comment by Glich440** [comment]
it seems like top source in that context refers to the one graphically above the others

**Comment by majabojarska** [comment]
Hi @DubbaThony! I'm wondering, what was the reason for closing this PR? Was it because of the unanswered questions and/or lack of timely cooperation from the maintainers?

I'd be willing to take over, especially that so much of the work is already done.

**Comment by DubbaThony** [comment]
Hi!

Yeah, I had unanwsered questions lingering for soo much time that I figured the strings are probably too outdated to be of any use anyway. And I could update it, but some wordings require some context, and if I cant get the anwsers to fill in context, the translations may be simply wrong.

I dont speak Java to figure it on my own tbh.

Feel free to take over, but bear in mind its been a long time.

**Comment by majabojarska** [comment]
Thanks for the quick answer! I'll try to setup the dev stack and see what's what.

**Pull request closed without merging**
